use_frameworks!

target 'InBrainSurveys_SDK_Swift_Example' do
  pod 'InBrainSurveys_SDK_Swift', :path => '../'

  target 'InBrainSurveys_SDK_Swift_Tests' do
    inherit! :search_paths

    
  end
end
