# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'InBrainSurveys_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InBrainSurveys_Demo
	pod 'InBrainSurveys_SDK_Swift'
  target 'InBrainSurveys_DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'InBrainSurveys_SDK_Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InBrainSurveys_SDK_Swift

  target 'InBrainSurveys_SDK_SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
