use_frameworks!

target 'InBrainSurveys-SDK-Swift_Example' do
  pod 'InBrainSurveys-SDK-Swift', :path => '../'

  target 'InBrainSurveys-SDK-Swift_Tests' do
    inherit! :search_paths

    
  end
end
